spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/resources?serverTimezone=UTC}
    #url: jdbc:postgresql://localhost:5432/resources
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:root}
    #username: postgres
    #password: gnar2004SION2003!
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  main:
    allow-circular-references: true

springdoc:
  pathsToMatch: /api/**

bezkoder:
  app:
    jwtSecret: 31c0d4f543124e11a47e2832bd82c29eff24951af97ec8e7c21459836e37896a
    jwtExpirationMs: 3600000 
