spring:
  datasource:
    #url: jdbc:postgresql://resources-relationnelles.ct4gy8emwdut.eu-north-1.rds.amazonaws.com:5432/resources
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/BaseTestRessource?serverTimezone=UTC}
    #url: jdbc:postgresql://localhost:5432/resources
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
    # password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  main:
    allow-circular-references: true

springdoc:
  pathsToMatch: /api/**

bezkoder:
  app:
    jwtSecret: 31c0d4f543124e11a47e2832bd82c29eff24951af97ec8e7c21459836e37896a
    jwtExpirationMs: 3600000 
